#!/usr/bin/env python3
"""
G3DT LaTeX Report Generator
Generates LaTeX files from data dictionaries, using the g3dt-report.cls template.

Usage:
    python generate_latex.py --sample --output report.tex
    python generate_latex.py --sample --compile  # Also runs xelatex
"""

import argparse
import subprocess
import shutil
from pathlib import Path
from typing import Dict, List, Any


def escape_latex(text: str) -> str:
    """Escape special LaTeX characters."""
    if text is None:
        return ""

    # Characters that need escaping in LaTeX
    replacements = [
        ('\\', r'\textbackslash{}'),
        ('&', r'\&'),
        ('%', r'\%'),
        ('$', r'\$'),
        ('#', r'\#'),
        ('_', r'\_'),
        ('{', r'\{'),
        ('}', r'\}'),
        ('~', r'\textasciitilde{}'),
        ('^', r'\textasciicircum{}'),
    ]

    for char, escaped in replacements:
        text = text.replace(char, escaped)

    # Handle line breaks
    text = text.replace('\n', r'\\')

    return text


def format_table_row(cells: List[str], header: bool = False) -> str:
    """Format a table row in LaTeX."""
    escaped = [escape_latex(str(c)) for c in cells]
    if header:
        escaped = [f"\\tableheader{{{c}}}" for c in escaped]
    return " & ".join(escaped) + r" \\"


class G3DTLatexGenerator:
    """Generate G3DT geotechnical reports in LaTeX format."""

    def __init__(self, template_dir: Path = None):
        self.template_dir = template_dir or Path(__file__).parent
        self.content = []

    def add_line(self, line: str = ""):
        """Add a line to the document."""
        self.content.append(line)

    def add_lines(self, lines: List[str]):
        """Add multiple lines."""
        self.content.extend(lines)

    def generate_preamble(self) -> List[str]:
        """Generate document preamble."""
        return [
            r"% G3DT Geotechnical Report",
            r"% Auto-generated by generate_latex.py",
            r"% Compile with: xelatex <filename>.tex",
            r"",
            r"\documentclass{g3dt-report}",
            r"",
            r"\begin{document}",
            r"",
        ]

    def generate_cover(self, data: Dict) -> List[str]:
        """Generate cover page."""
        client = escape_latex(data.get('client', '------'))
        expedient = escape_latex(data.get('expedient', ''))
        date = escape_latex(data.get('data', ''))
        obra = data.get('obra', '').replace('\n', r'\\' + '\n     ')
        obra = escape_latex(obra).replace(r'\\\\', r'\\')  # Handle double escaping
        location = data.get('obra', '').split('\n')[-1].split('(')[0].strip() if data.get('obra') else 'LOCALITAT'
        location = escape_latex(location)

        return [
            r"% ============================================================================",
            r"% COVER PAGE",
            r"% ============================================================================",
            r"",
            r"\makecover",
            f"    {{{client}}}",
            f"    {{{expedient}}}",
            f"    {{{date}}}",
            f"    {{{obra}}}",
            f"    {{{location}}}",
            r"",
        ]

    def generate_toc(self) -> List[str]:
        """Generate table of contents."""
        return [
            r"% ============================================================================",
            r"% TABLE OF CONTENTS",
            r"% ============================================================================",
            r"",
            r"\tableofcontents",
            r"\newpage",
            r"",
        ]

    def generate_section_1(self, data: Dict) -> List[str]:
        """Generate Section 1: Presentació de l'estudi."""
        lines = [
            r"% ============================================================================",
            r"% 1. PRESENTACIÓ DE L'ESTUDI",
            r"% ============================================================================",
            r"",
            r"\section{PRESENTACIÓ DE L'ESTUDI}",
            r"",
            f"A petició de: \\textbf{{{escape_latex(data.get('client', '------'))}}}",
            r"",
            r"G3 DT, S.L. ha realitzat el següent informe geotècnic segons les normes i recomanacions ",
            r"establertes en el DB SE-C Cimientos fetes pel ``Código Técnico de la Edificación'' (CTE), ",
            r"en vigor el 29 de març del 2006.",
            r"",
            r"\subsection{ANTECEDENTS}",
            r"",
        ]

        # Building description
        lines.append(r"Segons ens indica el sol·licitant, es vol valorar les característiques geològiques ")
        lines.append(r"i geotècniques d'una zona on es preveu la construcció d'un habitatge unifamiliar aïllat.")
        lines.append(r"")
        lines.append(r"L'edificació que es preveu construir presentarà les següents característiques:")
        lines.append(r"")

        # Building characteristics table
        lines.append(r"\begin{table}[H]")
        lines.append(r"\centering")
        lines.append(r"\begin{tabular}{ll}")
        lines.append(r"\toprule")
        lines.append(r"\tableheader{Paràmetre} & \tableheader{Valor} \\")
        lines.append(r"\midrule")

        building_data = [
            ("Tipus d'edificació", data.get('tipus_edificacio', 'Habitatge unifamiliar aïllat')),
            ("Nombre de plantes", data.get('plantes', 'Pb + 1Pp')),
            ("Superfície construïda", data.get('superficie', '---')),
        ]

        for label, value in building_data:
            lines.append(f"{escape_latex(label)} & {escape_latex(value)} \\\\")

        lines.append(r"\bottomrule")
        lines.append(r"\end{tabular}")
        lines.append(r"\caption{Resum de les principals dades de l'edificació a construir.}")
        lines.append(r"\end{table}")
        lines.append(r"")

        # Location figure placeholder
        lines.append(r"\begin{figure}[H]")
        lines.append(r"\centering")
        lines.append(r"% \includegraphics[width=0.8\textwidth]{figures/figura1-situacio.png}")
        lines.append(r"\fbox{\parbox{0.8\textwidth}{\centering\vspace{3cm}[Figura 1: Situació zona d'estudi]\vspace{3cm}}}")
        lines.append(r"\caption{Situació de la zona d'estudi (Mapa topogràfic i ortofoto, ICGC).}")
        lines.append(r"\end{figure}")
        lines.append(r"")

        # CTE Classification
        lines.append(r"\subsection{CLASSIFICACIÓ DE L'OBRA SEGONS EL CTE}")
        lines.append(r"")
        lines.append(r"A partir de les dades exposades pel client, un tècnic qualificat ha realitzat la següent classificació:")
        lines.append(r"")
        lines.append(r"\begin{table}[H]")
        lines.append(r"\centering")
        lines.append(r"\begin{tabular}{ll}")
        lines.append(r"\toprule")
        lines.append(r"\tableheader{Classificació} & \tableheader{Valor} \\")
        lines.append(r"\midrule")
        lines.append(f"Tipus d'edificació considerada & {escape_latex(data.get('cte_edificacio', 'C-0'))} \\\\")
        lines.append(f"Tipus de sòl considerat & {escape_latex(data.get('cte_sol', 'T-1'))} \\\\")
        lines.append(r"\bottomrule")
        lines.append(r"\end{tabular}")
        lines.append(r"\caption{Classificació de la construcció segons DB-SE-C del CTE.}")
        lines.append(r"\end{table}")
        lines.append(r"")

        # Objectives
        lines.append(r"\subsection{OBJECTIUS}")
        lines.append(r"")
        lines.append(r"Per la realització del present estudi, s'ha dut a terme una campanya de reconeixement del terreny, tenint en compte que els objectius de l'estudi són:")
        lines.append(r"")
        lines.append(r"\begin{itemize}")

        objectives = [
            "Estudi de l'entorn geològic de l'obra.",
            "Reconeixement, caracterització i potència dels materials del subsòl de la zona.",
            "Cota del nivell freàtic, quan es detecti dins de les cotes assolides per la campanya.",
            "Determinació de les càrregues admissibles dels materials sotmesos a càrrega.",
            "Estimació dels assentaments per a les càrregues admissibles calculades.",
            "Recomanacions sobre condicionants geològics i geotècnics.",
        ]

        for obj in objectives:
            lines.append(f"    \\item {escape_latex(obj)}")

        lines.append(r"\end{itemize}")
        lines.append(r"")

        return lines

    def generate_section_2(self, data: Dict) -> List[str]:
        """Generate Section 2: Treballs de camp."""
        lines = [
            r"% ============================================================================",
            r"% 2. TREBALLS DE CAMP",
            r"% ============================================================================",
            r"",
            r"\section{TREBALLS DE CAMP}",
            r"",
            r"\subsection{TIPUS D'OBRA I RECONEIXEMENT DE CAMP}",
            r"",
            f"Tal com s'ha indicat en l'apartat 1.2, l'obra es defineix com a tipus \\textbf{{{escape_latex(data.get('cte_edificacio', 'C-0'))}}}, ",
            r"que es correspon amb una construcció de menys de 4 plantes i superfície construïda inferior a 300 m².",
            r"",
            r"\subsection{SITUACIÓ DELS PUNTS DE RECONEIXEMENT}",
            r"",
            r"Els treballs de camp s'han centrat en la zona on s'ubicarà l'edificació prevista, així com les seves zones d'afecció.",
            r"",
            r"\begin{figure}[H]",
            r"\centering",
            r"\fbox{\parbox{0.8\textwidth}{\centering\vspace{3cm}[Figura 2: Emplaçament assaigs]\vspace{3cm}}}",
            r"\caption{Emplaçament dels assaigs realitzats.}",
            r"\end{figure}",
            r"",
            r"\subsection{RELACIÓ DE TREBALLS}",
            r"",
            r"A continuació s'enumeren els treballs de camp que s'han dut a terme:",
            r"",
            r"\begin{itemize}",
        ]

        tests = data.get('assaigs_insitu', ["2 assaigs de penetració dinàmica tipus DPSH"])
        for test in tests:
            lines.append(f"    \\item {escape_latex(test)}")

        lines.append(r"\end{itemize}")
        lines.append(r"")

        # DPSH description
        lines.append(r"\subsection{METODOLOGIA I DESCRIPCIÓ DELS TREBALLS DE CAMP}")
        lines.append(r"")
        lines.append(r"\subsubsection{PENETRÒMETRE DINÀMIC SUPERPESANT DPSH}")
        lines.append(r"")
        lines.append(r"L'assaig de penetració dinàmica és un tipus d'assaig de penetració contínua que permet conèixer la resistència del sòl que es va travessant.")
        lines.append(r"")
        lines.append(r"L'equip utilitzat correspon al DPSH normalitzat pel comitè europeu de normalització, consistent en una maça de 63,5 kg de pes, una alçada de caiguda lliure de 76 cm i una punta cònica de 90º d'angle i 50 mm de diàmetre.")
        lines.append(r"")

        # DPSH results table
        dpsh_results = data.get('dpsh_results', [])
        if dpsh_results:
            lines.append(r"\begin{table}[H]")
            lines.append(r"\centering")
            lines.append(r"\begin{tabular}{lllll}")
            lines.append(r"\toprule")
            lines.append(r"\tableheader{Assaig} & \tableheader{X (ETRS89)} & \tableheader{Y (ETRS89)} & \tableheader{Cota (m.s.n.m.)} & \tableheader{Prof. (m)} \\")
            lines.append(r"\midrule")

            for row in dpsh_results:
                escaped_row = [escape_latex(str(c)) for c in row]
                lines.append(" & ".join(escaped_row) + r" \\")

            lines.append(r"\bottomrule")
            lines.append(r"\end{tabular}")
            lines.append(r"\caption{Relació d'assaigs de penetració dinàmica DPSH realitzats.}")
            lines.append(r"\end{table}")
            lines.append(r"")

        return lines

    def generate_section_3(self, data: Dict) -> List[str]:
        """Generate Section 3: Descripció geològica i geotècnica."""
        lines = [
            r"% ============================================================================",
            r"% 3. DESCRIPCIÓ GEOLÒGICA I GEOTÈCNICA",
            r"% ============================================================================",
            r"",
            r"\section{DESCRIPCIÓ GEOLÒGICA I GEOTÈCNICA}",
            r"",
            r"\subsection{GEOLOGIA REGIONAL}",
            r"",
        ]

        lines.append(escape_latex(data.get('marc_geologic',
            "La zona d'estudi es situa geològicament a la Depressió del Vallès, una fossa tectònica que separa la Serralada Prelitoral de la Serralada Litoral.")))
        lines.append(r"")

        lines.append(r"\subsection{GEOLOGIA LOCAL}")
        lines.append(r"")
        lines.append(r"Segons el mapa geològic 1:50.000 de l'ICGC, a la zona d'estudi afloren materials quaternaris del Pleistocè superior.")
        lines.append(r"")

        lines.append(r"\subsection{CARACTERITZACIÓ GEOTÈCNICA}")
        lines.append(r"")
        lines.append(r"A partir dels resultats obtinguts en la campanya de reconeixement del terreny, s'estableix la següent caracterització geotècnica:")
        lines.append(r"")

        nivel_nom = data.get('nivell1_nom', 'Graves i sorres amb matriu llimosa')
        lines.append(f"\\textbf{{Unitat Geotècnica 1: {escape_latex(nivel_nom)}}}")
        lines.append(r"")
        lines.append(escape_latex(data.get('nivell1_litologia',
            "Material granular de coloració marró, format per graves i sorres amb matriu llimosa.")))
        lines.append(r"")

        # Geotechnical parameters table
        geotech_params = data.get('geotech_params', [
            ("Classificació USCS", "GP-GM", "", ""),
            ("Densitat aparent", "γ", "kN/m³", "20"),
            ("Angle de fricció interna", "φ'", "°", "32-35"),
            ("Cohesió efectiva", "c'", "kPa", "0"),
        ])

        lines.append(r"\begin{table}[H]")
        lines.append(r"\centering")
        lines.append(r"\begin{tabular}{ll}")
        lines.append(r"\toprule")
        lines.append(r"\tableheader{Paràmetre} & \tableheader{Valor} \\")
        lines.append(r"\midrule")

        for param in geotech_params:
            if len(param) >= 4:
                label = f"{param[0]} ({param[1]})" if param[1] else param[0]
                value = f"{param[3]} {param[2]}" if param[2] else param[3]
            else:
                label = param[0]
                value = param[1] if len(param) > 1 else ""
            lines.append(f"{escape_latex(label)} & {escape_latex(value)} \\\\")

        lines.append(r"\bottomrule")
        lines.append(r"\end{tabular}")
        lines.append(r"\caption{Paràmetres geotècnics adoptats.}")
        lines.append(r"\end{table}")
        lines.append(r"")

        # Phreatic level
        lines.append(r"\subsection{NIVELL FREÀTIC}")
        lines.append(r"")
        lines.append(escape_latex(data.get('nf_conclusio',
            "Durant la realització dels treballs de camp no s'ha detectat la presència de nivell freàtic dins de les cotes assolides pels assaigs de penetració.")))
        lines.append(r"")

        # Aggressivity
        lines.append(r"\subsection{AGRESSIVITAT DEL TERRENY}")
        lines.append(r"")
        lines.append(escape_latex(data.get('agressivitat_conclusio',
            "No s'han realitzat assaigs per determinar l'agressivitat química del terreny. Es recomana considerar una classe d'exposició IIa segons l'EHE-08.")))
        lines.append(r"")

        # Seismicity
        lines.append(r"\subsection{SISMICITAT}")
        lines.append(r"")
        sismica = data.get('sismica', {'ab': '< 0.04 g'})
        ab = sismica.get('ab', '< 0.04 g') if isinstance(sismica, dict) else '< 0.04 g'
        lines.append(f"Segons la Norma de Construcció Sismorresistent NCSE-02, la zona d'estudi presenta una acceleració sísmica bàsica a\\textsubscript{{b}} = {escape_latex(ab)}.")
        lines.append(r"")

        # Radon
        lines.append(r"\subsection{RADÓ}")
        lines.append(r"")
        rado_zona = data.get('rado_zona', 'Zona 1')
        lines.append(f"Segons el mapa de zonificació del potencial de radó d'Espanya, la zona d'estudi es classifica com a \\textbf{{{escape_latex(rado_zona)}}} (potencial baix).")
        lines.append(r"")

        return lines

    def generate_section_4(self, data: Dict) -> List[str]:
        """Generate Section 4: Conclusions."""
        lines = [
            r"% ============================================================================",
            r"% 4. CONCLUSIONS",
            r"% ============================================================================",
            r"",
            r"\section{CONCLUSIONS}",
            r"",
            r"\subsection{RESUM I VALORACIÓ}",
            r"",
            r"A partir dels treballs realitzats i de l'anàlisi de les dades obtingudes, es conclou que:",
            r"",
            r"\begin{enumerate}",
        ]

        conclusions = [
            "El terreny investigat presenta una successió estratigràfica formada per dipòsits quaternaris de naturalesa granular.",
            "Els materials presents mostren una compacitat densa a molt densa.",
            "No s'ha detectat nivell freàtic dins de les cotes assolides.",
            "Les condicions geotècniques són favorables per a l'execució de l'obra projectada.",
        ]

        for concl in conclusions:
            lines.append(f"    \\item {escape_latex(concl)}")

        lines.append(r"\end{enumerate}")
        lines.append(r"")

        lines.append(r"\subsection{CONDICIONS DE L'ESTUDI}")
        lines.append(r"")
        lines.append(r"Les conclusions d'aquest estudi són vàlides per a les condicions del terreny observades durant la campanya de reconeixement.")
        lines.append(r"")

        lines.append(r"\subsection{FONAMENTACIÓ}")
        lines.append(r"")

        lines.append(r"\subsubsection{Tipus de fonamentació}")
        lines.append(r"")
        lines.append(f"Es recomana una fonamentació de tipus \\textbf{{superficial}} mitjançant {escape_latex(data.get('tipus_fonament', 'sabates aïllades o corregudes'))}.")
        lines.append(r"")

        lines.append(r"\subsubsection{Cota de fonamentació}")
        lines.append(r"")
        prof = data.get('profunditat_encast', '0.60 m')
        lines.append(f"La cota mínima de fonamentació es fixa a \\textbf{{{escape_latex(prof)}}} respecte la cota de terreny actual.")
        lines.append(r"")

        lines.append(r"\subsubsection{Tensió admissible}")
        lines.append(r"")
        lines.append(r"La tensió admissible del terreny es fixa en:")
        lines.append(r"")
        qa = data.get('qa', '3.50')
        lines.append(r"\begin{center}")
        lines.append(f"\\textbf{{$\\sigma_{{adm}}$ = {escape_latex(qa)} kg/cm² ({float(qa.replace(',', '.')) * 100:.0f} kPa)}}")
        lines.append(r"\end{center}")
        lines.append(r"")

        lines.append(r"\subsubsection{Assentaments}")
        lines.append(r"")
        lines.append(escape_latex(data.get('assentaments',
            "Els assentaments esperats per a les càrregues admissibles calculades seran inferiors a 25 mm.")))
        lines.append(r"")

        return lines

    def generate_signature(self, data: Dict) -> List[str]:
        """Generate signature page."""
        lloc = data.get('lloc_signatura', 'Els Omells de Na Gaia')
        date = data.get('data_signatura', 'novembre del 2025')
        signant = data.get('signant_rol', 'G3 DT S.L.')

        return [
            r"% ============================================================================",
            r"% SIGNATURE PAGE",
            r"% ============================================================================",
            r"",
            r"\signaturepage",
            f"    {{{escape_latex(lloc)}}}",
            f"    {{{escape_latex(date)}}}",
            f"    {{{escape_latex(signant)}}}",
            r"",
        ]

    def generate_annexes(self) -> List[str]:
        """Generate annex placeholders."""
        annexes = [
            ("ANNEX 1", "Base de càlcul"),
            ("ANNEX 2", "Registre d'assaigs mecànics"),
            ("ANNEX 3", "Esquema situació assaigs"),
            ("ANNEX 4", "Tall de correlació"),
            ("ANNEX 5", "Fotografies"),
            ("ANNEX 6", "Actes d'assaig de laboratori"),
        ]

        lines = [
            r"% ============================================================================",
            r"% ANNEXES",
            r"% ============================================================================",
            r"",
            r"\appendix",
            r"",
            r"\section*{ANNEXES}",
            r"\addcontentsline{toc}{section}{ANNEXES}",
            r"",
        ]

        for num, title in annexes:
            lines.append(f"\\subsection*{{{num}: {escape_latex(title)}}}")
            lines.append(f"\\addcontentsline{{toc}}{{subsection}}{{{num}: {escape_latex(title)}}}")
            lines.append(f"[Contingut de l'{num.lower()}]")
            lines.append(r"")

        return lines

    def generate(self, data: Dict, output_path: Path) -> Path:
        """Generate complete LaTeX document."""
        self.content = []

        # Build document
        self.add_lines(self.generate_preamble())
        self.add_lines(self.generate_cover(data))
        self.add_lines(self.generate_toc())
        self.add_lines(self.generate_section_1(data))
        self.add_lines(self.generate_section_2(data))
        self.add_lines(self.generate_section_3(data))
        self.add_lines(self.generate_section_4(data))
        self.add_lines(self.generate_signature(data))
        self.add_lines(self.generate_annexes())

        # End document
        self.add_line(r"\end{document}")

        # Write to file
        output_path = Path(output_path)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(self.content))

        print(f"LaTeX file generated: {output_path}")
        return output_path

    def compile(self, tex_path: Path, output_dir: Path = None) -> Path:
        """Compile LaTeX to PDF using xelatex."""
        tex_path = Path(tex_path)
        output_dir = Path(output_dir) if output_dir else tex_path.parent

        # Run xelatex twice (for cross-references)
        for i in range(2):
            cmd = [
                'xelatex',
                '-interaction=nonstopmode',
                f'-output-directory={output_dir}',
                str(tex_path)
            ]

            print(f"Running xelatex (pass {i+1}/2)...")
            result = subprocess.run(
                cmd,
                cwd=tex_path.parent,
                capture_output=True,
                text=True
            )

            if result.returncode != 0:
                print(f"Warning: xelatex returned {result.returncode}")
                # Print last 20 lines of output for debugging
                lines = result.stdout.split('\n')[-20:]
                print('\n'.join(lines))

        pdf_path = output_dir / tex_path.with_suffix('.pdf').name
        if pdf_path.exists():
            print(f"PDF generated: {pdf_path}")
            return pdf_path
        else:
            print("Warning: PDF not found after compilation")
            return None


# Sample data based on 3001631 (Rubí) - same structure as generate_report.py
SAMPLE_DATA_RUBI = {
    # Cover
    'client': '------',
    'expedient': '3001631',
    'data': '21/11/25',
    'obra': 'ESTUDI GEOLÒGIC / GEOTÈCNIC\nPER A LA CONSTRUCCIÓ D\'UN HABITATGE\nUNIFAMILIAR MODULAR AÏLLAT',

    # Section 1
    'tipus_edificacio': 'Habitatge unifamiliar aïllat modular',
    'plantes': 'PB + Porxo',
    'superficie': '92 m²',
    'fonamentacio': 'Superficial',
    'profunditat_max': '5.40 m',
    'cte_edificacio': 'C-0',
    'cte_sol': 'T-1',

    # Section 2
    'data_camp': '15/11/2025',
    'assaigs_insitu': [
        "3 penetròmetres DPSH (Norma UNE-EN ISO 22476-2)"
    ],
    'dpsh_results': [
        ("P-1", "420823", "4594126", "212.5", "5.40"),
        ("P-2", "420831", "4594132", "212.3", "3.40"),
        ("P-3", "420838", "4594125", "212.4", "3.80"),
    ],

    # Section 3
    'marc_geologic': 'La zona d\'estudi es situa geològicament a la Depressió del Vallès, '
                     'una fossa tectònica que separa la Serralada Prelitoral de la Serralada Litoral. '
                     'Els materials que afloren a la zona corresponen principalment a dipòsits quaternaris '
                     'de naturalesa al·luvial i col·luvial, disposats sobre un substrat miocè.',
    'nivell1_nom': 'Graves i sorres amb matriu llimosa',
    'nivell1_litologia': 'Material granular de coloració marró, format per graves i sorres amb matriu llimosa. '
                         'Presenta una compacitat densa a molt densa segons els valors de N₂₀ obtinguts.',
    'geotech_params': [
        ("Classificació USCS", "", "", "GP-GM"),
        ("Densitat aparent", "γ", "kN/m³", "20"),
        ("Angle de fricció interna", "φ'", "°", "32-35"),
        ("Cohesió efectiva", "c'", "kPa", "0"),
    ],
    'nf_conclusio': 'Durant la realització dels treballs de camp no s\'ha detectat la presència de nivell freàtic dins de les cotes assolides pels assaigs de penetració.',
    'agressivitat_conclusio': 'No s\'han realitzat assaigs per determinar l\'agressivitat química del terreny. Es recomana considerar una classe d\'exposició IIa segons l\'EHE-08 per defecte.',
    'sismica': {'ab': '0.04g'},
    'rado_zona': 'Zona 1',

    # Section 4
    'tipus_fonament': 'sabates aïllades o corregudes',
    'profunditat_encast': '-0.80 m',
    'qa': '3.50',
    'assentaments': 'Els assentaments esperats per a les càrregues admissibles calculades seran inferiors a 25 mm, valor acceptable per a l\'estructura projectada.',

    # Signature
    'lloc_signatura': 'Els Omells de Na Gaia',
    'data_signatura': 'novembre del 2025',
    'signant_rol': 'G3 DT S.L.',
}


def main():
    parser = argparse.ArgumentParser(
        description='Generate G3DT geotechnical report in LaTeX format',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python generate_latex.py --sample --output report.tex
    python generate_latex.py --sample --compile
    python generate_latex.py --sample --compile --output-dir /tmp/reports
        """
    )
    parser.add_argument('--output', '-o', default='generated-report.tex',
                        help='Output .tex file path (default: generated-report.tex)')
    parser.add_argument('--sample', action='store_true',
                        help='Use sample data from 3001631 (Rubí)')
    parser.add_argument('--compile', '-c', action='store_true',
                        help='Also compile to PDF using xelatex')
    parser.add_argument('--output-dir', '-d',
                        help='Output directory for compiled PDF')
    parser.add_argument('--copy-to',
                        help='Copy generated PDF to this location')

    args = parser.parse_args()

    # Use sample data
    if args.sample:
        data = SAMPLE_DATA_RUBI
    else:
        data = SAMPLE_DATA_RUBI
        print("Using sample data. Implement JSON/YAML input for production use.")

    # Generate LaTeX
    generator = G3DTLatexGenerator()
    tex_path = Path(args.output)

    # Ensure output is in the same directory as the script (for assets)
    if not tex_path.is_absolute():
        tex_path = Path(__file__).parent / tex_path

    generator.generate(data, tex_path)

    # Compile if requested
    if args.compile:
        output_dir = Path(args.output_dir) if args.output_dir else tex_path.parent
        pdf_path = generator.compile(tex_path, output_dir)

        # Copy if requested
        if pdf_path and args.copy_to:
            dest = Path(args.copy_to)
            shutil.copy(pdf_path, dest)
            print(f"PDF copied to: {dest}")


if __name__ == '__main__':
    main()
